### ISSUE TITLE
LoginWithEmailAdress not working?

### ISSUE THREAD

**Issue by Tebreca** [PlayFab/PhpSdk#2]
hello there,

So, for the game I'm working on I want a full 100% security.
What I decided to do is design a REST API in PHP as an interaction layer between common and playfab.

I've set up my code, and everything should work, I'm sending this json: ```{"Email":"ewan.arends10@gmail.com","Password":"password123","titleId":"censored"}``` 
and for some reason I'm retrieving this: 
````{
    "code": 400,
    "status": "BadRequest",
    "error": "InvalidParams",
    "errorCode": 1000,
    "errorMessage": "Invalid input parameters",
    "errorDetails": {
        "Email": ["The Email address field is required."],
        "Password": ["The Password field is required."]
    }
}
````
i'm not the best php developer, but it looks like this is not my code (for once).
if it is, then i'm sorry for wasting your time.

thanks regardless

**Comment by pgilmorepf** [comment]
https://api.playfab.com/documentation/client/method/LoginWithEmailAddress

So, paradoxically, it seems that your TitleId should be the thing that's wrong, not the Email or Password.
It's... possible... that titleId -> TitleId might fix the issue, but that seems unlikely.

Honestly, since PHP is still in beta, you'd have to debug into our code and make sure that the json blob is being sent correctly according to the documentation link at the beginning of my post.

Apologies, our PHP is still very much in the experimental phase.

**Comment by pgilmorepf** [comment]
Apologies, we are no longer supporting this SDK and will not be issuing any fixes. Feel free to fork this SDK, fix any issues, and develop in your own account.
